import snapshot from '../../../shared/tariff-snapshots/tariffs.json';
import {
  UPS_EXACT_RATES,
  UPS_RANGE_RATES,
  UPS_DOC_EXACT_RATES,
  UPS_DOC_MAX_KG,
} from '../ups_tariff';
import {
  DHL_EXACT_RATES,
  DHL_RANGE_RATES,
  DHL_DOC_EXACT_RATES,
  DHL_DOC_MAX_KG,
} from '../dhl_tariff';
import {
  FEDEX_EXACT_RATES,
  FEDEX_RANGE_RATES,
  FEDEX_ENVELOPE_EXACT_RATES,
  FEDEX_PAK_EXACT_RATES,
  FEDEX_DOC_MAX_KG,
  FEDEX_ENVELOPE_MAX_KG,
} from '../fedex_tariff';

/**
 * Full-table drift gate between src/config/*_tariff.ts and the backend
 * lib/constants/*_tariff.rb, via the canonical snapshot generated by
 * `bin/rails tariff:snapshot` (shared/tariff-snapshots/tariffs.json).
 *
 * The per-fixture parity spec samples ~15 quote scenarios; this asserts every
 * cell of every rate table, so a single edited cell on either side fails CI.
 * The backend asserts the same file in spec/lib/tariff_snapshot_parity_spec.rb.
 *
 * Rate-update flow: edit the .rb tables → `bin/rails tariff:snapshot` →
 * mirror in the .ts tables → both suites green again.
 */

// Mirrors TariffSnapshot.canonical: numeric-string keys stay as-is (JS object
// keys are already strings, "0.5"/"5"), object keys sorted, array order kept.
const canonical = (value: unknown): unknown => {
  if (Array.isArray(value)) return value.map(canonical);
  if (value !== null && typeof value === 'object') {
    return Object.fromEntries(
      Object.entries(value as Record<string, unknown>)
        .map(([k, v]) => [k, canonical(v)] as const)
        .sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0)),
    );
  }
  return value;
};

describe('tariff table parity (frontend ↔ backend snapshot)', () => {
  it('UPS tables match the backend snapshot', () => {
    expect(canonical(UPS_EXACT_RATES)).toEqual(snapshot.ups.UPS_EXACT_RATES);
    expect(canonical(UPS_RANGE_RATES)).toEqual(snapshot.ups.UPS_RANGE_RATES);
    expect(canonical(UPS_DOC_EXACT_RATES)).toEqual(snapshot.ups.UPS_DOC_EXACT_RATES);
    expect(UPS_DOC_MAX_KG).toBe(snapshot.ups.UPS_DOC_MAX_KG);
  });

  it('DHL tables match the backend snapshot', () => {
    expect(canonical(DHL_EXACT_RATES)).toEqual(snapshot.dhl.DHL_EXACT_RATES);
    expect(canonical(DHL_RANGE_RATES)).toEqual(snapshot.dhl.DHL_RANGE_RATES);
    expect(canonical(DHL_DOC_EXACT_RATES)).toEqual(snapshot.dhl.DHL_DOC_EXACT_RATES);
    expect(DHL_DOC_MAX_KG).toBe(snapshot.dhl.DHL_DOC_MAX_KG);
  });

  it('FedEx tables match the backend snapshot', () => {
    expect(canonical(FEDEX_EXACT_RATES)).toEqual(snapshot.fedex.FEDEX_EXACT_RATES);
    expect(canonical(FEDEX_RANGE_RATES)).toEqual(snapshot.fedex.FEDEX_RANGE_RATES);
    expect(canonical(FEDEX_ENVELOPE_EXACT_RATES)).toEqual(
      snapshot.fedex.FEDEX_ENVELOPE_EXACT_RATES,
    );
    expect(canonical(FEDEX_PAK_EXACT_RATES)).toEqual(snapshot.fedex.FEDEX_PAK_EXACT_RATES);
    expect(FEDEX_DOC_MAX_KG).toBe(snapshot.fedex.FEDEX_DOC_MAX_KG);
    expect(FEDEX_ENVELOPE_MAX_KG).toBe(snapshot.fedex.FEDEX_ENVELOPE_MAX_KG);
  });
});
