import snapshot from '../../../shared/tariff-snapshots/tariffs.json';
import {
  UPS_EXACT_RATES,
  UPS_RANGE_RATES,
  UPS_DOC_EXACT_RATES,
  UPS_DOC_MAX_KG,
} from '../ups_tariff';
import {
  DHL_EXACT_RATES,
  DHL_RANGE_RATES,
  DHL_DOC_EXACT_RATES,
  DHL_DOC_MAX_KG,
} from '../dhl_tariff';
import {
  FEDEX_EXACT_RATES,
  FEDEX_RANGE_RATES,
  FEDEX_ENVELOPE_EXACT_RATES,
  FEDEX_PAK_EXACT_RATES,
  FEDEX_DOC_MAX_KG,
  FEDEX_ENVELOPE_MAX_KG,
} from '../fedex_tariff';
import {
  FUMIGATION_FEE,
  WAR_RISK_SURCHARGE_RATE,
  PACKING_MATERIAL_BASE_COST,
  PACKING_LABOR_UNIT_COST,
  DEFAULT_EXCHANGE_RATE,
  DEFAULT_FSC_PERCENT,
  DEFAULT_FSC_PERCENT_DHL,
  DEFAULT_FSC_PERCENT_FEDEX,
} from '../rates';
// Not from rates.ts: the frontend keeps the margin ceiling in business-rules.ts
// while the backend keeps it in rates.rb. Different file names on each side is
// what made this pair invisible to a rates.ts↔rates.rb comparison.
import { MAX_MARGIN_PERCENT } from '../business-rules';

/**
 * Full drift gate between the frontend config and the backend
 * lib/constants/*.rb, via the canonical snapshot generated by
 * `bin/rails tariff:snapshot` (shared/tariff-snapshots/tariffs.json).
 *
 * The per-fixture parity spec samples ~15 quote scenarios; this asserts every
 * cell of every rate table and every mirrored rate constant, so a single edited
 * value on either side fails CI. The backend asserts the same file in
 * spec/lib/tariff_snapshot_parity_spec.rb.
 *
 * Update flow — the backend is the source of truth:
 *   1. edit lib/constants/*_tariff.rb (tables) or lib/constants/rates.rb (constants)
 *   2. `bin/rails tariff:snapshot`
 *   3. mirror on the frontend: src/config/*_tariff.ts, src/config/rates.ts, or
 *      src/config/business-rules.ts (MAX_MARGIN_PERCENT lives there, not rates.ts)
 *   4. both suites green again
 */

// Mirrors TariffSnapshot.canonical: numeric-string keys stay as-is (JS object
// keys are already strings, "0.5"/"5"), object keys sorted, array order kept.
const canonical = (value: unknown): unknown => {
  if (Array.isArray(value)) return value.map(canonical);
  if (value !== null && typeof value === 'object') {
    return Object.fromEntries(
      Object.entries(value as Record<string, unknown>)
        .map(([k, v]) => [k, canonical(v)] as const)
        .sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0)),
    );
  }
  return value;
};

describe('tariff table parity (frontend ↔ backend snapshot)', () => {
  it('UPS tables match the backend snapshot', () => {
    expect(canonical(UPS_EXACT_RATES)).toEqual(snapshot.ups.UPS_EXACT_RATES);
    expect(canonical(UPS_RANGE_RATES)).toEqual(snapshot.ups.UPS_RANGE_RATES);
    expect(canonical(UPS_DOC_EXACT_RATES)).toEqual(snapshot.ups.UPS_DOC_EXACT_RATES);
    expect(UPS_DOC_MAX_KG).toBe(snapshot.ups.UPS_DOC_MAX_KG);
  });

  it('DHL tables match the backend snapshot', () => {
    expect(canonical(DHL_EXACT_RATES)).toEqual(snapshot.dhl.DHL_EXACT_RATES);
    expect(canonical(DHL_RANGE_RATES)).toEqual(snapshot.dhl.DHL_RANGE_RATES);
    expect(canonical(DHL_DOC_EXACT_RATES)).toEqual(snapshot.dhl.DHL_DOC_EXACT_RATES);
    expect(DHL_DOC_MAX_KG).toBe(snapshot.dhl.DHL_DOC_MAX_KG);
  });

  it('FedEx tables match the backend snapshot', () => {
    expect(canonical(FEDEX_EXACT_RATES)).toEqual(snapshot.fedex.FEDEX_EXACT_RATES);
    expect(canonical(FEDEX_RANGE_RATES)).toEqual(snapshot.fedex.FEDEX_RANGE_RATES);
    expect(canonical(FEDEX_ENVELOPE_EXACT_RATES)).toEqual(
      snapshot.fedex.FEDEX_ENVELOPE_EXACT_RATES,
    );
    expect(canonical(FEDEX_PAK_EXACT_RATES)).toEqual(snapshot.fedex.FEDEX_PAK_EXACT_RATES);
    expect(FEDEX_DOC_MAX_KG).toBe(snapshot.fedex.FEDEX_DOC_MAX_KG);
    expect(FEDEX_ENVELOPE_MAX_KG).toBe(snapshot.fedex.FEDEX_ENVELOPE_MAX_KG);
  });

  /**
   * rates.ts ↔ rates.rb. Until 2026-09-09 this was the one mirrored pair with
   * no drift gate — the tables had the snapshot and the calculation had
   * shared/test-fixtures/calculation-parity.json, but the FX and FSC constants
   * were guarded only by `fx-apply.py --check`, a personal skill outside the
   * repo that CI never runs. DEFAULT_EXCHANGE_RATE scales every USD figure a
   * customer sees and moves weekly; DEFAULT_FSC_PERCENT* are the fallback used
   * whenever the DB lookup fails. Half-updating either quietly splits the
   * on-screen quote from the saved one.
   *
   * Listed one key at a time rather than deep-equalling the section: a new
   * constant added to rates.rb should make someone decide whether it belongs
   * in the gate, not slip in because the object still matched.
   */
  it('rate constants match the backend snapshot', () => {
    expect(FUMIGATION_FEE).toBe(snapshot.rates.FUMIGATION_FEE);
    expect(WAR_RISK_SURCHARGE_RATE).toBe(snapshot.rates.WAR_RISK_SURCHARGE_RATE);
    expect(PACKING_MATERIAL_BASE_COST).toBe(snapshot.rates.PACKING_MATERIAL_BASE_COST);
    expect(PACKING_LABOR_UNIT_COST).toBe(snapshot.rates.PACKING_LABOR_UNIT_COST);
    expect(DEFAULT_EXCHANGE_RATE).toBe(snapshot.rates.DEFAULT_EXCHANGE_RATE);
    expect(DEFAULT_FSC_PERCENT).toBe(snapshot.rates.DEFAULT_FSC_PERCENT);
    expect(DEFAULT_FSC_PERCENT_DHL).toBe(snapshot.rates.DEFAULT_FSC_PERCENT_DHL);
    expect(DEFAULT_FSC_PERCENT_FEDEX).toBe(snapshot.rates.DEFAULT_FSC_PERCENT_FEDEX);
    expect(MAX_MARGIN_PERCENT).toBe(snapshot.rates.MAX_MARGIN_PERCENT);
  });

  // The list above is only a gate while it stays complete. Without this, adding
  // a constant to the snapshot on the backend and forgetting the assertion here
  // leaves it ungated with both suites green.
  it('asserts every rate constant the snapshot carries', () => {
    expect(Object.keys(snapshot.rates).sort()).toEqual(
      [
        'DEFAULT_EXCHANGE_RATE',
        'DEFAULT_FSC_PERCENT',
        'DEFAULT_FSC_PERCENT_DHL',
        'DEFAULT_FSC_PERCENT_FEDEX',
        'FUMIGATION_FEE',
        'MAX_MARGIN_PERCENT',
        'PACKING_LABOR_UNIT_COST',
        'PACKING_MATERIAL_BASE_COST',
        'WAR_RISK_SURCHARGE_RATE',
      ].sort(),
    );
  });
});
